version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/username/laravel:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

    db:
        image: mysql:5.7.22
        volumes:
            - ./mysql:/var/lib/mysql
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
